
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
    -   id: ruff-check
        args: [--fix]
    -   id: ruff-format
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
    -   id: codespell
        args: [src/, docs/]
        pass_filenames: false
        additional_dependencies: [tomli]
