# Copyright 2024, MASSACHUSETTS INSTITUTE OF TECHNOLOGY
# Subject to FAR 52.227-11 – Patent Rights – Ownership by the Contractor (May 2014).
# SPDX-License-Identifier: MIT
"""Golden-value tests: seeded models must keep producing these exact numbers.

A PR that changes model output must update the literals here AND explain the
change in its description. Phase 3 PRs are expected to do so; any other PR
that moves them has changed behaviour it did not mean to change.
"""

import pytest
import torch
from golden_data import (
    far_ood_batch,
    query_batch,
    separable_dataset,
    trained_gp,
    trained_protonet,
)

# Generated by golden_data.trained_*().predict(golden_data.query_batch()) on CPU.
PROTONET_CLASSES = [
    [0.9999671, 2.6514104e-05, 6.416818e-06],
    [1.8700959e-08, 1.0, 3.2100119e-12],
    [2.2039617e-15, 3.0007299e-12, 1.0],
]
PROTONET_OOD = [0.1947163, 0.10947485, 0.21058975]
GP_CLASSES = [
    [0.69452822, 0.10328995, 0.2021818],
    [0.11296804, 0.82432896, 0.062703006],
    [0.19589241, 0.043056507, 0.76105112],
]
GP_OOD = [0.73808295, 0.5272457, 0.60310042]


@pytest.mark.parametrize(
    "make, expected_classes, expected_ood",
    [
        pytest.param(trained_protonet, PROTONET_CLASSES, PROTONET_OOD, id="protonet"),
        pytest.param(trained_gp, GP_CLASSES, GP_OOD, id="gp"),
    ],
)
def test_predictions_match_golden_values(make, expected_classes, expected_ood) -> None:
    out = make().predict(query_batch())
    assert torch.allclose(out.classes, torch.tensor(expected_classes), atol=1e-6)
    assert torch.allclose(out.ood_scores, torch.tensor(expected_ood), atol=1e-6)


@pytest.mark.parametrize("make", [trained_protonet, trained_gp], ids=["protonet", "gp"])
def test_far_out_of_distribution_queries_score_higher(make) -> None:
    """#187: OOD scores must separate far-OOD queries from in-distribution ones."""
    model = make()
    in_dist = model.predict(query_batch()).ood_scores
    far = model.predict(far_ood_batch()).ood_scores
    assert torch.all(in_dist >= 0) and torch.all(in_dist <= 1)
    assert torch.all(far >= 0) and torch.all(far <= 1)
    assert far.mean() > in_dist.mean()


def test_protonet_ood_scores_lie_in_unit_interval_on_training_data() -> None:
    _, x, _ = separable_dataset()
    ood = trained_protonet().predict(x).ood_scores
    assert torch.all(ood >= 0) and torch.all(ood <= 1)
